### ISSUE TITLE
DiscordSRV can't process player count placeholder

### ISSUE THREAD

**Issue by RhinoCD** [quantiom/AdvancedVanish#21]
The %advancedvanish_player_count% place holder seems to require a Player for it to work, due to this, trying to add the placeholder display a number through the discord channel topic, It doesn't work.

Stated by discordsrv support: "I checked their source and it seems that it displays the same thing for everyone, just the number of connected players minus the number of vanished players."

"Cause of the other placeholder, to check if the player is vanished. so naturally they said that player has to be there whether it's checking for either placeholder, might be slightly silly of them 👀 though idk how this works enough to know if it's justified"

What Its suppose to look like: 
![image](https://user-images.githubusercontent.com/78483451/189742940-d3572dea-4c73-4491-b96e-8542f8984342.png)

Instead it errors when trying to use advancedvanish placeholder ^

**Comment by quantiom** [comment]
Hi, could you please send the error? Thanks.

**Comment by granny** [comment]
```
[DiscordSRV - Channel Topic Updater/WARN]: Exception in thread "DiscordSRV - Channel Topic Updater" java.lang.NullPointerException: Parameter specified as non-null is null: method me.quantiom.advancedvanish.hook.impl.PlaceHolderApiHook$expansion$1.onPlaceholderRequest, parameter player
[DiscordSRV - Channel Topic Updater/WARN]:     at AdvancedVanish (8).jar//me.quantiom.advancedvanish.hook.impl.PlaceHolderApiHook$expansion$1.onPlaceholderRequest(PlaceHolderApiHook.kt)
[DiscordSRV - Channel Topic Updater/WARN]:     at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:35)
[DiscordSRV - Channel Topic Updater/WARN]:     at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:119)
[DiscordSRV - Channel Topic Updater/WARN]:     at PlaceholderAPI-2.11.2.jar//me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:71)
[DiscordSRV - Channel Topic Updater/WARN]:     at DiscordSRV-Build-1.26.0-SNAPSHOT-2970143.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replacePlaceholders(PlaceholderUtil.java:40)
[DiscordSRV - Channel Topic Updater/WARN]:     at DiscordSRV-Build-1.26.0-SNAPSHOT-2970143.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replacePlaceholdersToDiscord(PlaceholderUtil.java:64)
[DiscordSRV - Channel Topic Updater/WARN]:     at DiscordSRV-Build-1.26.0-SNAPSHOT-2970143.jar//github.scarsz.discordsrv.util.PlaceholderUtil.replacePlaceholdersToDiscord(PlaceholderUtil.java:50)
[DiscordSRV - Channel Topic Updater/WARN]:     at DiscordSRV-Build-1.26.0-SNAPSHOT-2970143.jar//github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.applyPlaceholders(ChannelTopicUpdater.java:72)
[DiscordSRV - Channel Topic Updater/WARN]:     at DiscordSRV-Build-1.26.0-SNAPSHOT-2970143.jar//github.scarsz.discordsrv.objects.threads.ChannelTopicUpdater.run(ChannelTopicUpdater.java:47)
```

**Comment by quantiom** [comment]
Hi, could you please send me your discord, or add me (quantiom#0001) so I can send you a build to verify that it's fixed? Thank you.

**Comment by RhinoCD** [comment]
yes, iv sent you a friend request
