### ISSUE TITLE
[1.8.8] There was an error performing this command.

### ISSUE THREAD

**Issue by Neeonn** [quantiom/AdvancedVanish#9]
Spigot version: FlamePaper 1.8.8 (API version 1.8.8-R0.1-SNAPSHOT)

```[09:43:12 INFO]: Neeonn issued server command: /vanish
[09:43:12 ERROR]: [ACF] Exception in command: vanish 
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.util.AdvancedVanishAPI.vanishPlayer(AdvancedVanishAPI.kt:47)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.util.AdvancedVanishAPI.vanishPlayer$default(AdvancedVanishAPI.kt:32)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.command.VanishCommand.onVanishCommand(VanishCommand.kt:43)
[09:43:12 ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:43:12 ERROR]: [ACF]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:43:12 ERROR]: [ACF]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:43:12 ERROR]: [ACF]         at java.lang.reflect.Method.invoke(Method.java:498)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.acf.BaseCommand.execute(BaseCommand.java:513)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.acf.RootCommand.execute(RootCommand.java:99)
[09:43:12 ERROR]: [ACF]         at me.quantiom.advancedvanish.acf.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[09:43:12 ERROR]: [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[09:43:12 ERROR]: [ACF]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[09:43:12 ERROR]: [ACF]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:43:12 ERROR]: [ACF]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:762)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:701)
[09:43:12 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:604)
[09:43:12 ERROR]: [ACF]         at java.lang.Thread.run(Thread.java:748)```

**Comment by quantiom** [comment]
Which version of AdvancedVanish are you using? And can you please send more of the stacktrace? There should be another one under the one you sent.

**Comment by quantiom** [comment]
Closed due to inactivity.
